{"name": "test_call_pytest_fail_with_reason", "status": "passed", "description": "\n    >>> import pytest\n\n    >>> def test_call_pytest_fail_with_reason_example():\n    ...     pytest.fail(\"Fail message\")\n    ", "attachments": [{"name": "stdout", "source": "5a98cb94-2a50-4438-94c4-f3e2318e42fe-attachment.txt", "type": "text/plain"}], "start": 1710872969687, "stop": 1710872969706, "uuid": "64517227-66f1-45c1-89c8-ec089f0f775d", "historyId": "ec78e536b24daed782b4d43dc986c367", "testCaseId": "ec78e536b24daed782b4d43dc986c367", "fullName": "tests.allure_pytest.acceptance.status.base_call_status_test#test_call_pytest_fail_with_reason", "labels": [{"name": "parentSuite", "value": "tests.allure_pytest.acceptance.status"}, {"name": "suite", "value": "base_call_status_test"}, {"name": "host", "value": "MacBook-Pro-whenessel.local"}, {"name": "thread", "value": "29518-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.allure_pytest.acceptance.status.base_call_status_test"}]}